[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "20.9.0"
  # Explicitly disable Python to avoid confusion
  PYTHON_VERSION = "false"

[images]
  remote_images = [
    "https://images.unsplash.com/photo-*"
  ]
