[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "20.0.0"  # Specifying a Node.js version that meets Next.js requirements

[images]
  remote_images = [
    "https://images.unsplash.com/photo-*"
  ]
