// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/24/2025, 8:09:07 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/spider/Downloads/SWIFTZONE/WebSite/swiftzone/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/spider/Downloads/SWIFTZONE/WebSite/swiftzone/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/spider/Downloads/SWIFTZONE/WebSite/swiftzone/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/spider/Downloads/SWIFTZONE/WebSite/swiftzone/plugins/**/*.{js,ts,mjs}","/Users/spider/Downloads/SWIFTZONE/WebSite/swiftzone/composables/**/*.{js,ts,mjs}","/Users/spider/Downloads/SWIFTZONE/WebSite/swiftzone/utils/**/*.{js,ts,mjs}","/Users/spider/Downloads/SWIFTZONE/WebSite/swiftzone/pages/index.vue","/Users/spider/Downloads/SWIFTZONE/WebSite/swiftzone/pages/contact.vue","/Users/spider/Downloads/SWIFTZONE/WebSite/swiftzone/pages/blogtest.vue","/Users/spider/Downloads/SWIFTZONE/WebSite/swiftzone/pages/blog/index.vue","/Users/spider/Downloads/SWIFTZONE/WebSite/swiftzone/pages/blog/[slug].vue","/Users/spider/Downloads/SWIFTZONE/WebSite/swiftzone/pages/services/ux-ui-design.vue","/Users/spider/Downloads/SWIFTZONE/WebSite/swiftzone/pages/services/web-development.vue","/Users/spider/Downloads/SWIFTZONE/WebSite/swiftzone/pages/services/digital-strategy.vue","/Users/spider/Downloads/SWIFTZONE/WebSite/swiftzone/pages/services/digital-marketing.vue","/Users/spider/Downloads/SWIFTZONE/WebSite/swiftzone/pages/services/software-development.vue","/Users/spider/Downloads/SWIFTZONE/WebSite/swiftzone/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/spider/Downloads/SWIFTZONE/WebSite/swiftzone/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/spider/Downloads/SWIFTZONE/WebSite/swiftzone/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;